required_fields:
  - title
  - project_id
  - tasklist_id
  - module
  - severity
  - env
  - steps
  - expected
  - actual

default_values:
  severity: "普通"

field_mapping:
  title: "content"
  project_id: "projectId"
  tasklist_id: "tasklistId"
  module: "custom_module"
  severity: "priority"
  env: "custom_env"
  steps: "custom_steps"
  expected: "custom_expected"
  actual: "custom_actual"
