base_url: "https://open.teambition.com/api"
project_id: "tb_project_id"
bug_sfc_id: ""
default_stage_id: ""
default_tasklist_id: "tb_tasklist_id"
default_executor_id: ""
taskflowstatus_id: ""
priority_map: {}
customfields: {}
