u001:
  name: "QA User"
  roles:
    - qa

u002:
  name: "Dev User"
  roles:
    - dev

admin001:
  name: "Admin User"
  roles:
    - admin

"36665056041252632":
  name: "DingTalk QA User"
  roles:
    - qa
